version: "3.7"
services:
        opencv:
                image: roadsong/opencv-alpine:latest
                container_name: csml-opencv
                hostname: csml-opencv
                ports:
                        - 9980:9980/udp
                volumes:
                        - type: volume
                          source: csml-opencv-results
                          target: /results/opencv
                #command: ["python3", "/app_code/opencv_app.py"]
                command: 
                        - mkdir /app_code
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/config.py
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/opencv_app.py
                restart: unless-stopped
                tty: true
        dynet:
                image: roadsong/dynet-alpine:latest
                container_name: csml-dynet
                hostname: cmsl-dynet
                ports:
                        - 9981:9981/udp
                volumes:
                        - type: volume
                          source: csml-dynet-results
                          target: /results/dynet
                command:
                        - mkdir /app_code
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/config.py
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/dynet_app.py
                restart: unless-stopped
                tty: true
        dlib:
                image: roadsong/dlib-alpine:latest
                container_name: csml-dlib
                hostname: csml-dlib
                ports:
                        - 9982:9982/udp
                volumes:
                        - type: volume
                          source: csml-dlib-results
                          target: /results/dlib
                command:
                        - mkdir /app_code
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/config.py
                        - wget -P /app_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/app/dlib_app.py
                restart: unless-stopped
                tty: true
        management:
                #image: roadsong/csml-management:latest
                image: alpine:latest
                container_name: csml-management
                hostname: csml-management
                ports:
                        - 9983:9983/udp
                volumes:
                        - type: volume
                          source: csml-dlib-results
                          target: /results/dlib
                        - type: volume
                          source: csml-dynet-results
                          target: /results/dynet
                        - type: volume
                          source: csml-opencv-results
                          target: /results/opencv
                command:
                        - mkdir /management_code
                        - wget -P /management_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/management/config.py
                        - wget -P /management_code https://raw.githubusercontent.com/Roadsong/CSML/master/code/management/main.py
                restart: unless-stopped
                tty: true
volumes:
        csml-dlib-results:
                external: true
        csml-dynet-results:
                external: true
        csml-opencv-results:
                external: true
networks:
        default:
                external:
                        name: csml-cluster