version: "3.7"
services:
        opencv:
                image: roadsong/opencv-alpine:latest
                container_name: csml-opencv
                hostname: csml-opencv
                ports:
                        - 9980:9980/udp
                volumes:
                        - csml-results:/results/opencv
                command: ["python3", "opencv_app.py"]
                restart: unless-stopped
                tty: true
        dynet:
                image: roadsong/dynet-alpine:latest
                container_name: csml-dynet
                hostname: cmsl-dynet
                ports:
                        - 9981:9981/udp
                volumes:
                        - csml-results:/results/dynet
                command: ["sh", "dynet_app.py"]
                restart: unless-stopped
                tty: true
        dlib:
                image: roadsong/dlib-alpine:latest
                container_name: csml-dlib
                hostname: csml-dlib
                ports:
                        - 9982:9982/udp
                volumes:
                        - csml-results:/results/dlib
                command: ["sh", "dlib_app.py"]
                restart: unless-stopped
                tty: true
        management:
                image: roadsong/csml-management:latest
                container_name: csml-management
                hostname: csml-management
                ports:
                        - 9983:9983/udp
                volumes:
                        - csml-results:/results
                command: ["python3", "main.py"]
                restart: unless-stopped
                tty: true
networks:
        default:
                external:
                        name: csml-cluster