version: "3.7"
services:
        opencv:
                image: roadsong/opencv-alpine:latest
                container_name: csml-opencv
                hostname: csml-opencv
                ports:
                        - 9980:9980/udp
                volumes:
                        - type: volume
                          source: csml-opencv-results
                          target: /results/opencv
                command:
                        ["sh", "/app_code/opencv_start.sh"]  
                restart: unless-stopped
                tty: true
        dynet:
                image: roadsong/dynet-alpine:latest
                container_name: csml-dynet
                hostname: cmsl-dynet
                ports:
                        - 9981:9981/udp
                volumes:
                        - type: volume
                          source: csml-dynet-results
                          target: /results/dynet
                command:
                        ["sh", "/app_code/dynet_start.sh"] 
                restart: unless-stopped
                tty: true
        dlib:
                image: roadsong/dlib-alpine:latest
                container_name: csml-dlib
                hostname: csml-dlib
                ports:
                        - 9982:9982/udp
                volumes:
                        - type: volume
                          source: csml-dlib-results
                          target: /results/dlib
                command:
                        ["sh", "/app_code/dlib_start.sh"]
                restart: unless-stopped
                tty: true
        management:
                image: roadsong/csml-management:latest
                container_name: csml-management
                hostname: csml-management
                ports:
                        - 9983:9983/udp
                volumes:
                        - type: volume
                          source: csml-dlib-results
                          target: /results/dlib
                        - type: volume
                          source: csml-dynet-results
                          target: /results/dynet
                        - type: volume
                          source: csml-opencv-results
                          target: /results/opencv
                command:
                        ["sh", "/management_code/management_start.sh"] 
                restart: unless-stopped
                tty: true
volumes:
        csml-dlib-results:
                external: true
        csml-dynet-results:
                external: true
        csml-opencv-results:
                external: true
networks:
        default:
                external:
                        name: csml-cluster